### ISSUE TITLE
Design a new logo for OneStopHelp

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#1]
**Task**

You are supposed to design a new logo (apart from the readme.md file one). Look for some awesome designs for cool ideas.
(Include logo designs of both - text type and icon type)

**Implementation**

Tools used: Adobe Photoshop, Adobe Illustrator, Canva or any other tool convenient to you.
Create designs and share screenshots in the comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR

**Comment by Mitali-laroia** [comment]
I would like to work on this issue.

**Comment by muskaanv0** [comment]
I would like to work on this issue.

**Comment by shivangisahay14** [comment]
I would like to work on this issue.

**Comment by nandini-412** [comment]
I would like to work on the logo

**Comment by Sonali12920** [comment]
> I would like to work on this issue.

Go for it !!

**Comment by Sonali12920** [comment]
> I would like to work on this issue.

Go for it!!

**Comment by Sonali12920** [comment]
> I would like to work on this issue.

Go for it!!

**Comment by Sonali12920** [comment]
Guys go for it. Design a new and cool logo for OneStopHelp. All the best!!😉

**Comment by nporia** [comment]
I would like to work on it too.

**Comment by muskaanv0** [comment]
Pls check the following logos that i designed !!
![image](https://user-images.githubusercontent.com/62637855/97168037-ccf01800-17ad-11eb-8c7e-3af9ed38db89.png)
![image](https://user-images.githubusercontent.com/62637855/97168048-d11c3580-17ad-11eb-8cbd-e1cc14dfabd1.png)
![image](https://user-images.githubusercontent.com/62637855/97168058-d5485300-17ad-11eb-8211-3ff952181ffc.png)
![image](https://user-images.githubusercontent.com/62637855/97168064-d8dbda00-17ad-11eb-82ab-19f22a9b1d96.png)

**Comment by Sonali12920** [comment]
> Pls check the following logos that i designed !!
> ![image](https://user-images.githubusercontent.com/62637855/97168037-ccf01800-17ad-11eb-8c7e-3af9ed38db89.png)
> ![image](https://user-images.githubusercontent.com/62637855/97168048-d11c3580-17ad-11eb-8cbd-e1cc14dfabd1.png)
> ![image](https://user-images.githubusercontent.com/62637855/97168058-d5485300-17ad-11eb-8211-3ff952181ffc.png)
> ![image](https://user-images.githubusercontent.com/62637855/97168064-d8dbda00-17ad-11eb-82ab-19f22a9b1d96.png)

2nd one looks nice. We will wait for all the assignees to make logo and then we will finalise one. 😉

**Comment by shivangisahay14** [comment]
I have designed 2 logos so far and would add more if required.
![logo2](https://user-images.githubusercontent.com/57834633/97179089-6e7f6580-17be-11eb-94e4-200e267195e6.jpeg)
![logo1](https://user-images.githubusercontent.com/57834633/97179102-717a5600-17be-11eb-96ac-82b684cc7890.jpeg)

**Comment by Sonali12920** [comment]
> I have designed 2 logos so far and would add more if required.
> ![logo2](https://user-images.githubusercontent.com/57834633/97179089-6e7f6580-17be-11eb-94e4-200e267195e6.jpeg)
> ![logo1](https://user-images.githubusercontent.com/57834633/97179102-717a5600-17be-11eb-96ac-82b684cc7890.jpeg)

Looks nice. We will wait for all the assignees to make logo and then we will finalise one. 😉Till then feel free to make more designs if you want.

**Comment by nporia** [comment]
I have designed a few also. Please give them a look.
![1](https://user-images.githubusercontent.com/20817990/97194401-210bf400-17d0-11eb-9f87-eeef777b6c1e.jpg)
![2](https://user-images.githubusercontent.com/20817990/97194407-223d2100-17d0-11eb-9806-744c50887262.jpg)
![3](https://user-images.githubusercontent.com/20817990/97194411-223d2100-17d0-11eb-8964-ba2898d13600.jpg)

**Comment by Mitali-laroia** [comment]
The logos I have designed so far:
![ONESTOPHELP](https://user-images.githubusercontent.com/54024297/97196305-53b6ec00-17d2-11eb-8497-696c6e2a1aa9.gif)
![ONESTOPHELP (1)](https://user-images.githubusercontent.com/54024297/97196313-56194600-17d2-11eb-863e-94adb87a7bba.gif)
![NESHOTHELP](https://user-images.githubusercontent.com/54024297/97196316-57e30980-17d2-11eb-97e1-3275eee8b8f4.gif)

**Comment by Sonali12920** [comment]
@nporia and @Mitali-laroia, Your designed logos look really really cool. 😁 We will finalise one soon. Thanks for contributing.

**Comment by nandini-412** [comment]
<img width="414" alt="Screenshot 2020-10-26 at 10 01 40 PM" src="https://user-images.githubusercontent.com/71938658/97206489-cc23aa00-17de-11eb-9659-1ca00e7a24f0.png">
<img width="378" alt="Screenshot 2020-10-26 at 10 32 18 PM" src="https://user-images.githubusercontent.com/71938658/97206519-d6de3f00-17de-11eb-9521-fafacc546ecb.png">
<img width="617" alt="Screenshot 2020-10-26 at 10 55 25 PM" src="https://user-images.githubusercontent.com/71938658/97206576-ebbad280-17de-11eb-8da4-0a8273bb3db5.png">
<img width="465" alt="Screenshot 2020-10-26 at 10 31 05 PM" src="https://user-images.githubusercontent.com/71938658/97206599-f2e1e080-17de-11eb-902f-bf21cd26d9f0.png">

**Comment by nandini-412** [comment]
I have made these logos so far and I'm working on more options. Please have a look^

**Comment by Sonali12920** [comment]
> I have made these logos so far and I'm working on more options. Please have a look^

@nandini-412 Logos look really good. Thanks for your contribution.😉

**Comment by heenahmed** [comment]
I would like to work on this issue.

**Comment by heenahmed** [comment]
<img width="422" alt="logo" src="https://user-images.githubusercontent.com/66954825/97424359-98f42e80-1936-11eb-8572-9acf42ec744e.PNG">


please review this. I will make more soon

**Comment by heenahmed** [comment]
<img width="281" alt="logo2" src="https://user-images.githubusercontent.com/66954825/97424966-7878a400-1937-11eb-934a-50a104dc39d4.PNG">

**Comment by Sonali12920** [comment]
> <img alt="logo" width="422" src="https://user-images.githubusercontent.com/66954825/97424359-98f42e80-1936-11eb-8572-9acf42ec744e.PNG">
> 
> please review this. I will make more soon

This one looks cool. But few changes that you can do are firstly write One-Stop Help straight in middle and also the red colour is not going good with pink and white, see if you can change it to another colour. 😊

**Comment by heenahmed** [comment]
ok, I will do the necessary changes.

**Comment by nandini-412** [comment]
![ne-3](https://user-images.githubusercontent.com/71938658/97567701-ce6b4b80-1a0c-11eb-9b4b-1d82b24bdb59.png)
