### ISSUE TITLE
Make a proper folder structure for the project

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#14]
Folders:-
1. **public** include folders:-
- css
- js
- img 

2. **view** includes files:-
- index.html
- resources.html
- updates.thml
- team.html
- contactus.html
-login/signup.html

3. Change the index.js file to **app.js file**(outside the folders)

**Comment by shivangisahay14** [comment]
I would like to work on this issue

**Comment by shagun0915** [comment]
> Folders:-
> 
> 1. **public** include folders:-
> 
> * css
> * js
> * img
> 
> 1. **view** includes files:-
> 
> * index.html
> * resources.html
> * updates.thml
> * team.html
> * contactus.html
>   -login/signup.html
> 
> 1. Change the index.js file to **app.js file**(outside the folders)

I want to work on this

**Comment by shagun0915** [comment]
Do I have to put the HTML, CSS, and js file in the respective folders? Also, I have to add an empty app.js file, or do I need to put the code inside it?

**Comment by Sonali12920** [comment]
> Do I have to put the HTML, CSS, and js file in the respective folders? Also, I have to add an empty app.js file, or do I need to put the code inside it?

Add all the HTML files in view folder and CSS and JS in the respective folders inside the public folder. Change index.js file's name to app.js and leave it empty for now!!
