### ISSUE TITLE
Changes in Navbar

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#15]
1. Logo at left

2. Next to the logo, there will be
Resources
Updates
Team
Contact Us

3. Login/SignUp at Right

**Comment by Mitali-laroia** [comment]
I would like to work on this issue

**Comment by shivangisahay14** [comment]
I would like to work on this issue

**Comment by shagun0915** [comment]
I would like to work on this issue.

**Comment by shagun0915** [comment]
@Sonali12920 Which one is the finalized logo that needs to be included in the navbar?

**Comment by Sonali12920** [comment]
@shagun0915 Updated the finalized logo in the readme.md. You can check it.
