### ISSUE TITLE
Design a login/sign Up Page

### ISSUE THREAD

**Issue by pccoder-2000** [dscigdtuw/OneStopHelp#16]
sign up page should accepts the inputs like :
 1. Name
 2. User Name
 3. email id
 4. password
 5. confirm password

login should accepts the inputs like :
 1, User name or email
 2. password

_You can also add some additional inputs if  needed._

**Comment by shivangisahay14** [comment]
I would like to work on this issue

**Comment by shagun0915** [comment]
I would like to work on this issue.

**Comment by muskaanv0** [comment]
I would like to work on this issue.

**Comment by muskaanv0** [comment]
I would like to work on this issue.
