### ISSUE TITLE
Contemplate a Tagline for OneStopHelp

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#2]
**Task**
Make a catchy tagline for the web app. It should go with the theme and the logo which will be finalized soon. Till then feel free to contemplate a catchy line.

**Procedure**
Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR

**Comment by shivangisahay14** [comment]
I would like to share my contribution

**Comment by Sonali12920** [comment]
> I would like to share my contribution

Go for it!!

**Comment by heenahmed** [comment]
I would like to work on this issue.

Tagline: 1.  All you need is here.
             2.  Treasury of resources
             3. We care, we share.
             4. everything just in one place.

**Comment by pcpriyankapc** [comment]
I would Like to work on this issue.
Taglines
1.If You've Got the Time, We've Got the Help.
2.Stop and Help. We build smiles.
3.With Stop and Help you'll have no more worries !
4.Gives a Heal , Stop and Help Appeal.
5.Have help your way.
