### ISSUE TITLE
Design Resource Page 

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#21]
Includes all Departments.
And under each department, there will be:-
Syllabus, Notes, Books, Previous Year Papers

(If you have a better idea, then do comment it)

**Comment by vanichitkara** [comment]
I would like to work on this issue

**Comment by heenahmed** [comment]
I would like to work on this issue. please guide , do we have to make a HTML,CSS web page or just a design of what we are thinking to create ?

**Comment by Sonali12920** [comment]
You have to make a complete working page which will obviously include HTML, CSS files.  All the necessary details you have to include on the page is already mentioned. Try to implement it in a better way.
