### ISSUE TITLE
Create .gitignore file

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#25]
Add a new file .gitignore in the project.
A .gitignore file is a plain text file where each line contains a pattern for files/directories to ignore.

**Comment by csunidhi13** [comment]
Can you assign this to me? I'd like to try!

**Comment by Bartek532** [comment]
Can you assign it to me? I have some idea about this issue 😃

**Comment by 5hraddha** [comment]
Is this still open

**Comment by Bartek532** [comment]
I created PR to this issue (#62) but it's have not reviewed yet.

**Comment by Sonali12920** [comment]
Thank you @Bartek532 for your contribution!
