### ISSUE TITLE
Design a basic layout of homepage

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#3]
**Tasks**

This is the first page that opens when a user visits the website. 

This includes:-

- Navigation Bar - Full-Length Navigation Bar for large and extra-large screens and full-Screen Overlay Navigation Bar for medium and smaller devices. (For this, you can check the site map in the readme.md)

- Brief Description of the project

- Footer

**Procedure**
Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR

**Comment by nporia** [comment]
I would like to work on this issue.

**Comment by yogita10** [comment]
I want to work on this issue

**Comment by pcpriyankapc** [comment]
I would like to work on this issue !

**Comment by nikita-1801** [comment]
I would like to work on this issue

**Comment by Sonali12920** [comment]
Go for it 

Fork this repository.
Create a branch: git checkout -b <branch_name>.
Make your changes
- Install Nodejs from https://nodejs.org/en/
- Once you have forked repo run commands - npm install, npm init, npm start(to start the server)
- Make index.html and design the main page of the web app
Commit them: git commit -m '<commit_message>'
Push to the original branch: git push origin <project_name>/
Create the pull request. 

All the best guys!!

**Comment by shagun0915** [comment]
I would like to work on the issue.

**Comment by nikita-1801** [comment]
Won't we be deciding on a design first so that we can take up individual components and work on them?

**Comment by Sonali12920** [comment]
> Won't we be deciding on a design first so that we can take up individual components and work on them?

Ya, we will surely do it. As of now, we want to add the main page which consists of a navbar, footer and a brief description of the project in between. For navbar, you can check the site map in readme.md.

**Comment by Sonali12920** [comment]
> **Tasks**
> 
> This is the first page that opens when a user visits the website. [the index.js]
> 
> This includes:-
> 
> * Navigation Bar - Full-Length Navigation Bar for large and extra-large screens and full-Screen Overlay Navigation Bar for medium and smaller devices. (For this, you can check the site map in the readme.md)
> * Brief Description of the project
> * Footer
> 
> **Procedure**
> Claim this issue: Comment below that you want to work on this issue
> Write relevant commit message while making a PR

**Comment by shagun0915** [comment]
I have made this basic layout. Please take a look at this and let me know about any changes that need to be made.


![Untitled design (1)](https://user-images.githubusercontent.com/56886360/97477856-2b67f280-1976-11eb-9948-d5bd6b758694.gif)

![Untitled design (2)](https://user-images.githubusercontent.com/56886360/97478290-bd6ffb00-1976-11eb-8e64-1afa381092ce.gif)

**Comment by Sonali12920** [comment]
@shagun0915  For the basic layout, it's nice. See if you can change the colour theme as background colours are very bright and text is not properly visible.

**Comment by nikita-1801** [comment]
I have some color palette suggestions for the template shagun suggested-

#1
![image](https://user-images.githubusercontent.com/66848627/97707560-78b2a400-1add-11eb-970e-0e0655efa438.png)

#2
![image](https://user-images.githubusercontent.com/66848627/97707709-b1527d80-1add-11eb-8c55-870d581d4d79.png)

#3
![image](https://user-images.githubusercontent.com/66848627/97707766-c62f1100-1add-11eb-99e6-ca4b0c207dcc.png)

**Comment by shagun0915** [comment]
> @shagun0915 For the basic layout, it's nice. See if you can change the colour theme as background colours are very bright and text is not properly visible.

I have used a different color scheme. Take a look.
![Screenshot 2020-10-31 141709](https://user-images.githubusercontent.com/56886360/97775104-f4ffc280-1b83-11eb-8b9e-37bfa3af15fa.png)
![Screenshot 2020-10-31 141740](https://user-images.githubusercontent.com/56886360/97775107-fe892a80-1b83-11eb-93ae-89cdd6f86363.png)

**Comment by pccoder-2000** [comment]
hey ! i have created a home page , Please do have a look ;)

![One-Stop-Can-Help-Opera-10-31-20](https://user-images.githubusercontent.com/66944725/97784873-ab38cb80-1bc7-11eb-985d-b833a934619f.gif)


![One-Stop-Can-Help-Opera-10-31-20 (1)](https://user-images.githubusercontent.com/66944725/97785059-cbb55580-1bc8-11eb-964b-95bba0ad826e.gif)

**Comment by nikita-1801** [comment]
Mock-up for the Title, About and CTA section

![header](https://user-images.githubusercontent.com/66848627/97792387-7a768780-1c03-11eb-9176-9ce47912036a.jpg)
![about](https://user-images.githubusercontent.com/66848627/97792389-7fd3d200-1c03-11eb-8e29-bbcae9aa327b.jpg)
![cta](https://user-images.githubusercontent.com/66848627/97792744-65502780-1c08-11eb-8328-880c17363245.jpg)

The illustrations are just for sample. So, the color scheme will depend on the illustrations we select.

**Comment by Sonali12920** [comment]
@nikita-1801 Its looks good. Make a footer. Or else just raise pr for this.
