### ISSUE TITLE
Changes required in Team Page

### ISSUE THREAD

**Issue by Sonali12920** [dscigdtuw/OneStopHelp#32]
Change theme according to the home page. 
1. Add navbar
2. Add Github Profile pictures instead of random pictures or make a folder in the project, add drive link and ask all to add their pictures in that drive and use those pictures.
3. Instead of Html, js logo just below the profile pictures, add their GitHub profile link.
4. Make cards of the same size(fix the height of cards).
5. Add footer

**Comment by Anjalikumari148** [comment]
I want to work on  this issue
